FROM node:22-alpine

WORKDIR /app

COPY . .
COPY package.json package-lock.json* ./
RUN npm install --legacy-peer-deps

COPY . .

ENV CHOKIDAR_USEPOLLING=true

CMD ["npx", "nx", "serve", "api", "--watch"]